//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltinnSimulator.OnlineBatchReceiver {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnlineBatchReceiver.OnlineBatchReceiverSoapSoap")]
    public interface OnlineBatchReceiverSoapSoap {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://AltInn.no/webservices/) of message ReceiveOnlineBatchExternalAttachmentRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://AltInn.no/webservices/ReceiveOnlineBatchExternalAttachment", ReplyAction="*")]
        AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentResponse ReceiveOnlineBatchExternalAttachment(AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AltInn.no/webservices/ReceiveOnlineBatchExternalAttachment", ReplyAction="*")]
        System.Threading.Tasks.Task<AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentResponse> ReceiveOnlineBatchExternalAttachmentAsync(AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AltinnSimulator.OnlineBatchReceiver.HelloWorldResponse HelloWorld(AltinnSimulator.OnlineBatchReceiver.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AltinnSimulator.OnlineBatchReceiver.HelloWorldResponse> HelloWorldAsync(AltinnSimulator.OnlineBatchReceiver.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveOnlineBatchExternalAttachment", WrapperNamespace="http://AltInn.no/webservices/", IsWrapped=true)]
    public partial class ReceiveOnlineBatchExternalAttachmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://AltInn.no/webservices/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://AltInn.no/webservices/", Order=1)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://AltInn.no/webservices/", Order=2)]
        public string receiversReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://AltInn.no/webservices/", Order=3)]
        public long sequenceNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://AltInn.no/webservices/", Order=4)]
        public string batch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://AltInn.no/webservices/", Order=5)]
        public byte[] attachments;
        
        public ReceiveOnlineBatchExternalAttachmentRequest() {
        }
        
        public ReceiveOnlineBatchExternalAttachmentRequest(string username, string passwd, string receiversReference, long sequenceNumber, string batch, byte[] attachments) {
            this.username = username;
            this.passwd = passwd;
            this.receiversReference = receiversReference;
            this.sequenceNumber = sequenceNumber;
            this.batch = batch;
            this.attachments = attachments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveOnlineBatchExternalAttachmentResponse", WrapperNamespace="http://AltInn.no/webservices/", IsWrapped=true)]
    public partial class ReceiveOnlineBatchExternalAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://AltInn.no/webservices/", Order=0)]
        public string ReceiveOnlineBatchExternalAttachmentResult;
        
        public ReceiveOnlineBatchExternalAttachmentResponse() {
        }
        
        public ReceiveOnlineBatchExternalAttachmentResponse(string ReceiveOnlineBatchExternalAttachmentResult) {
            this.ReceiveOnlineBatchExternalAttachmentResult = ReceiveOnlineBatchExternalAttachmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AltinnSimulator.OnlineBatchReceiver.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AltinnSimulator.OnlineBatchReceiver.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AltinnSimulator.OnlineBatchReceiver.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AltinnSimulator.OnlineBatchReceiver.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnlineBatchReceiverSoapSoapChannel : AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineBatchReceiverSoapSoapClient : System.ServiceModel.ClientBase<AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap>, AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap {
        
        public OnlineBatchReceiverSoapSoapClient() {
        }
        
        public OnlineBatchReceiverSoapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlineBatchReceiverSoapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineBatchReceiverSoapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineBatchReceiverSoapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentResponse AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap.ReceiveOnlineBatchExternalAttachment(AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentRequest request) {
            return base.Channel.ReceiveOnlineBatchExternalAttachment(request);
        }
        
        public string ReceiveOnlineBatchExternalAttachment(string username, string passwd, string receiversReference, long sequenceNumber, string batch, byte[] attachments) {
            AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentRequest inValue = new AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentRequest();
            inValue.username = username;
            inValue.passwd = passwd;
            inValue.receiversReference = receiversReference;
            inValue.sequenceNumber = sequenceNumber;
            inValue.batch = batch;
            inValue.attachments = attachments;
            AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentResponse retVal = ((AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap)(this)).ReceiveOnlineBatchExternalAttachment(inValue);
            return retVal.ReceiveOnlineBatchExternalAttachmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentResponse> AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap.ReceiveOnlineBatchExternalAttachmentAsync(AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentRequest request) {
            return base.Channel.ReceiveOnlineBatchExternalAttachmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentResponse> ReceiveOnlineBatchExternalAttachmentAsync(string username, string passwd, string receiversReference, long sequenceNumber, string batch, byte[] attachments) {
            AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentRequest inValue = new AltinnSimulator.OnlineBatchReceiver.ReceiveOnlineBatchExternalAttachmentRequest();
            inValue.username = username;
            inValue.passwd = passwd;
            inValue.receiversReference = receiversReference;
            inValue.sequenceNumber = sequenceNumber;
            inValue.batch = batch;
            inValue.attachments = attachments;
            return ((AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap)(this)).ReceiveOnlineBatchExternalAttachmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AltinnSimulator.OnlineBatchReceiver.HelloWorldResponse AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap.HelloWorld(AltinnSimulator.OnlineBatchReceiver.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AltinnSimulator.OnlineBatchReceiver.HelloWorldRequest inValue = new AltinnSimulator.OnlineBatchReceiver.HelloWorldRequest();
            inValue.Body = new AltinnSimulator.OnlineBatchReceiver.HelloWorldRequestBody();
            AltinnSimulator.OnlineBatchReceiver.HelloWorldResponse retVal = ((AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnSimulator.OnlineBatchReceiver.HelloWorldResponse> AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap.HelloWorldAsync(AltinnSimulator.OnlineBatchReceiver.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltinnSimulator.OnlineBatchReceiver.HelloWorldResponse> HelloWorldAsync() {
            AltinnSimulator.OnlineBatchReceiver.HelloWorldRequest inValue = new AltinnSimulator.OnlineBatchReceiver.HelloWorldRequest();
            inValue.Body = new AltinnSimulator.OnlineBatchReceiver.HelloWorldRequestBody();
            return ((AltinnSimulator.OnlineBatchReceiver.OnlineBatchReceiverSoapSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
