package no.altinn.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-03T15:39:36.537+02:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://AltInn.no/webservices/", name = "OnlineBatchReceiverSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface OnlineBatchReceiverSoap {

    @WebMethod(operationName = "ReceiveOnlineBatchExternalAttachment", action = "http://AltInn.no/webservices/ReceiveOnlineBatchExternalAttachment")
    @RequestWrapper(localName = "ReceiveOnlineBatchExternalAttachment", targetNamespace = "http://AltInn.no/webservices/", className = "no.altinn.webservices.ReceiveOnlineBatchExternalAttachment")
    @ResponseWrapper(localName = "ReceiveOnlineBatchExternalAttachmentResponse", targetNamespace = "http://AltInn.no/webservices/", className = "no.altinn.webservices.ReceiveOnlineBatchExternalAttachmentResponse")
    @WebResult(name = "ReceiveOnlineBatchExternalAttachmentResult", targetNamespace = "http://AltInn.no/webservices/")
    public java.lang.String receiveOnlineBatchExternalAttachment(
        @WebParam(name = "username", targetNamespace = "http://AltInn.no/webservices/")
        java.lang.String username,
        @WebParam(name = "passwd", targetNamespace = "http://AltInn.no/webservices/")
        java.lang.String passwd,
        @WebParam(name = "receiversReference", targetNamespace = "http://AltInn.no/webservices/")
        java.lang.String receiversReference,
        @WebParam(name = "sequenceNumber", targetNamespace = "http://AltInn.no/webservices/")
        long sequenceNumber,
        @WebParam(name = "batch", targetNamespace = "http://AltInn.no/webservices/")
        java.lang.String batch,
        @WebParam(name = "attachments", targetNamespace = "http://AltInn.no/webservices/")
        byte[] attachments
    );
}
